// Local fixture server only. Never uses production credentials or writes live data.
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const output=process.env.ATLAS_TEST_OUTPUT||'/private/tmp/map-v05-browser';await mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE});
const context=await browser.newContext({viewport:{width:1440,height:1000}});
await context.addCookies([{name:'atlas_fixture_author',value:'1',url:'http://127.0.0.1:8794'}]);
const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
await page.goto('http://127.0.0.1:8794/author/');await page.waitForFunction(()=>!document.querySelector('#fields').disabled);
assert.equal(await page.locator('#place-name').inputValue(),'流水修道院');
assert.equal(await page.locator('#photo-list img').count(),2);await page.locator('#current-pin').waitFor({state:'visible'});
await page.waitForFunction(()=>document.querySelectorAll('#coast path').length>0);
await page.screenshot({path:output+'/editor-desktop.png',fullPage:true});
let searches=0;page.on('request',r=>{if(r.url().includes('/author/api/search'))searches++;});
await page.locator('#location-query').fill('爱丁堡城堡');assert.equal(searches,0);
await page.locator('#location-search-button').click();await page.getByRole('button',{name:'选中并新增',exact:true}).click();
assert.equal(searches,1);assert.equal(await page.locator('#place-name').inputValue(),'Edinburgh Castle');
assert.equal(await page.locator('#region').inputValue(),'scotland');
assert.equal(await page.locator('#longitude').inputValue(),'-3.2004184');
assert.equal(await page.locator('#advanced-location').getAttribute('open'),null);
await page.locator('#place-name').fill('浏览器测试城堡');
await page.locator('#region').selectOption('scotland');
await page.locator('#overview').click({position:{x:270,y:260}});
assert.notEqual(await page.locator('#longitude').inputValue(),'');
await page.locator('#advanced-location summary').click();await page.locator('#longitude').fill('-3.1999');await page.locator('#latitude').fill('55.9486');
await page.locator('#review-author').fill('测试作者');await page.locator('#comment').fill('草稿不可公开');
await page.locator('#unrated').uncheck();await page.locator('#rating').fill('4.5');
await page.locator('#photos').setInputFiles(new URL('../public/assets/photos/fountains-abbey/exterior.v0.3.jpg',import.meta.url).pathname);
await page.waitForFunction(()=>document.querySelector('#message').textContent.includes('照片已上传'));
assert.equal(await page.locator('#photo-list img').count(),1);
await page.locator('#save-draft').click();await page.waitForFunction(()=>document.querySelector('#message').textContent.includes('草稿已保存'));
const id=await page.locator('#place-select').inputValue();
let pub=await (await fetch('http://127.0.0.1:8794/api/places')).json();assert(!pub.memories.some(p=>p.id===id));
await page.reload();await page.waitForFunction(()=>!document.querySelector('#fields').disabled);
await page.locator('#place-select').selectOption(id);assert.equal(await page.locator('#comment').inputValue(),'草稿不可公开');
assert.equal(await page.locator('#longitude').inputValue(),'-3.1999');
await page.locator('#place-form button[type=submit]').click();await page.waitForFunction(()=>document.querySelector('#message').textContent.includes('已发布'));
pub=await (await fetch('http://127.0.0.1:8794/api/places')).json();const published=pub.memories.find(p=>p.id===id);assert.equal(published.review.rating,4.5);assert.equal(published.photos.length,1);
assert.equal((await fetch('http://127.0.0.1:8794'+published.photos[0].src)).status,200);
await page.locator('#street-mode').click();await page.waitForFunction(()=>document.querySelector('#street-mode').getAttribute('aria-pressed')==='true');
assert(await page.locator('.street-tile-image').count()>0);await page.locator('#street').click({position:{x:250,y:230}});assert.notEqual(await page.locator('#longitude').inputValue(),'-3.1999');
await page.screenshot({path:output+'/editor-street.png',fullPage:true});
await page.locator('#overview-mode').click();
for(const width of [390,768,1024]){await page.setViewportSize({width,height:900});await page.screenshot({path:output+`/editor-${width}.png`,fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
const reader=await browser.newContext({viewport:{width:1440,height:1000}}),home=await reader.newPage();home.on('pageerror',e=>errors.push(e.message));
await home.goto(`http://127.0.0.1:8794/#place=${id}`);
try{await home.locator('#story-panel[open]').waitFor({timeout:12000});}catch(e){console.log('HOME DEBUG',errors,await home.locator('body').innerText());await browser.close();throw e;}
assert.equal(await home.locator('#story-place').innerText(),'浏览器测试城堡\nEdinburgh Castle');
await home.waitForFunction(()=>{const i=document.querySelector('#story-photo');return i.complete&&i.naturalWidth>0;});
await home.locator('#close-story').click();await home.locator('#rating-sort').selectOption('rating-asc');assert.notEqual(await home.locator('.memory-row').first().getAttribute('data-id'),'fountains-abbey');
await home.locator('#rating-sort').selectOption('rating-desc');assert.equal(await home.locator('.memory-row').first().getAttribute('data-id'),'fountains-abbey');
await home.reload();assert.equal(await home.locator('#rating-sort').inputValue(),'rating-desc');
await home.screenshot({path:output+'/home-sort.png',fullPage:true});
await home.setViewportSize({width:390,height:844});await home.screenshot({path:output+'/home-mobile.png',fullPage:true});assert(await home.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
assert.deepEqual(errors,[]);await browser.close();
console.log('PASS: editor desktop/mobile; map pick/street tiles; image upload; private draft reload; publish/read; deep link; star sort/persistence; no JS errors. Screenshots: '+output);
